apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "nh185064@ncr.com"
  # configure for letsencrypt's staging api
  lego.stag_url: "https://acme-staging.api.letsencrypt.org/directory"
  # configure for letsencrypt's production api
  lego.prod_url: "https://acme-v01.api.letsencrypt.org/directory"
  # set log level
  lego.log_level: "debug"
kind: ConfigMap
